### PR TITLE
use local/faster mirror and local timezone; add current maxmind database for geolocation

### PR DESCRIPTION
**Pull request by juju4**

### CODE REVIEW

**Comment by babadofar** [comment]
This is a very good idea, of course we want to use local mirror when possible.
However I get a few errors when trying to run the script:

this error
` sed: -e expression #1, char 33: unknown option to `s'`


Also. an error when it tries to delete the logstash.conf file. It is installed as part of the logstash setup in the default manifest. If you don't want it , you should rather modify the default.pp file .

**Comment by juju4** [comment]
That's strange for sed... pretty basic matching and working well on my host ubuntu box (14.04, gnu sed 4.2.2) which match the Vagrant vm box.  What is your setup? What happen if run manually vs Vagrantfile?

I will look into that and logstash.conf as soon as I have time.

**Comment by babadofar** [comment]
Just running vagrant up. No changes. The command works when SSH to the
machine but not in the vagrant setup.
19. jun. 2015 01.30 skrev "Julien" <notifications@github.com>:

**Comment by babadofar** [comment]
I removed the logstash.conf setting from the default manifest and changed the readme to include directions on how to add it yourself. So that's already taken care of :smiley_cat:

**Comment by babadofar** [comment]
I moved your code along with the other script into a separate bash script file, that made it work. Thanks!

**Pull request closed without merging**
